# basic options
title: Real Estate Technologies
author: Joseph Clegg and James Motes
email: josephrc@cleggunlimited.com
description: A wonderful site
github_username:  joeyclegg
github_username:  jamesmotes

# Build settings
markdown: kramdown
theme: minima
