# basic options
title: Real Estate Technologies
author: joeyclegg
email: josephrc@cleggunlimited.com
description: We are a new startup focused on integrating new technologies into the real estate software landscape.


# Build settings
markdown: kramdown
theme: minima
